### ISSUE TITLE
the side bar remains open after user clicks on an item

### ISSUE THREAD

**Issue by preetchani** [TheLeanProgrammer/portfolio#36]
Fix:- use isOpen prop and maintain menu state. Let me know if I can raise a pull request @MadhavBahl

**Comment by MadhavBahl** [comment]
Hmm, yes, it might be better if we autoclose the side bar after clicking

Although, instead of maintaining it in state, I think there must be some option already available in the react-burger-menu - check out the docs - https://www.npmjs.com/package/react-burger-menu

If not present, we can always do that by maintaining isOpen state, but using the library options would be better since we've already included the lib

**Comment by preetchani** [comment]
Hi @MadhavBahl Sir, 
Please take a look at my solution :slightly_smiling_face: #37
